# terraform/templates/hosts.yml.tpl

all:
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_bucket_name: ansible-ssm-bucket-ztakb3of
  children:
    bastion:
      hosts:
        bastion:
          ansible_host: 54.198.9.195
          ansible_user: ec2-user
    webapp:
      hosts:
        i-0247564859054afbc:
          ansible_connection: aws_ssm
          ansible_aws_ssm_instance_id: i-0247564859054afbc
          ansible_aws_ssm_region: us-east-1
        i-0dd15342a28a17a6f:
          ansible_connection: aws_ssm
          ansible_aws_ssm_instance_id: i-0dd15342a28a17a6f
          ansible_aws_ssm_region: us-east-1
